---
title: "Recidivism Final"
author: "Jeff Westerhof"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(epiDisplay)
library(caret)
library(ggplot2)
rec_raw <- read.csv("C:/Users/jwest/Documents/Final Project/NIJ_s_Recidivism_Challenge_Full_Dataset.csv", header = T,na.strings = c(""), stringsAsFactors = TRUE)
  
summary(rec_raw)
head(rec_raw)

#removing rows with more than 5 missing values
#removing rows with more than 4 removes 20% of dataset,threshold increased to 5
#and only 1810 rows removed
rec <- rec_raw[rowSums(is.na(rec_raw)) < 6, ]

#Imputing Supervision Level from Risk Score
sum(is.na(rec$Supervision_Level_First))
risk<-tabpct(rec$Supervision_Risk_Score_First,
             rec$Supervision_Level_First,main = 'Risk Score & Supervision Level', xlab = 'Supervision Level', ylab = 'Risk Score',
             col = c('#33cccc','#66cc99','#336666'), las = 1)
rec$Supervision_Level_First[is.na(rec$Supervision_Level_First) & rec$Supervision_Risk_Score_First<6] = 'Standard'
rec$Supervision_Level_First[is.na(rec$Supervision_Level_First) & rec$Supervision_Risk_Score_First>5 & rec$Supervision_Risk_Score_First < 9]= 'High'
rec$Supervision_Level_First[is.na(rec$Supervision_Level_First) & rec$Supervision_Risk_Score_First>8] = 'Specialized'
rec$Supervision_Level_First[is.na(rec$Supervision_Level_First) & is.na(rec$Supervision_Risk_Score_First)] = 'Standard'

#Imputing Gang Affiliation by mode
sum(is.na(rec$Gang_Affiliated))
which.max(table(rec$Gang_Affiliated))
rec$Gang_Affiliated[is.na(rec$Gang_Affiliated)] = 'false'


#Imputing Offence: category other
sum(is.na(rec$Prison_Offense))
rec$Prison_Offense[is.na(rec$Prison_Offense)]= 'Other'

#Imputing Drug tests. Because all the NAs for the drug tests are the same records,
#going on the assumption that drug testing was not part of their release conditions
#Since the median is 0, will assign 0 to these records and not the mean
sum(is.na(rec$Avg_Days_per_DrugTest))
sum(is.na(rec$DrugTests_THC_Positive))
sum(is.na(rec$DrugTests_Cocaine_Positive))
sum(is.na(rec$DrugTests_Meth_Positive))
sum(is.na(rec$DrugTests_Other_Positive)& is.na(rec$DrugTests_Meth_Positive)
    & is.na(rec$DrugTests_Cocaine_Positive)& is.na(rec$DrugTests_THC_Positive))
rec$Avg_Days_per_DrugTest[is.na(rec$Avg_Days_per_DrugTest) &
                            is.na(rec$DrugTests_Cocaine_Positive)]= 0
rec$DrugTests_THC_Positive[is.na(rec$DrugTests_THC_Positive)] = 0
rec$DrugTests_Cocaine_Positive[is.na(rec$DrugTests_Cocaine_Positive)]= 0
rec$DrugTests_Meth_Positive[is.na(rec$DrugTests_Meth_Positive)]=0
rec$DrugTests_Other_Positive[is.na(rec$DrugTests_Other_Positive)] = 0

#remaining NAs for Avg_Days_per_DrugTest assigned the mean
summary(rec$Avg_Days_per_DrugTest)
rec$Avg_Days_per_DrugTest[is.na(rec$Avg_Days_per_DrugTest)]= 75.12

#Imputing Employment Data
sum(is.na(rec$Percent_Days_Employed))
sum(is.na(rec$Jobs_Per_Year))
summary(rec$Percent_Days_Employed)
summary(rec$Jobs_Per_Year)
rec$Percent_Days_Employed[is.na(rec$Percent_Days_Employed)]= .4845
rec$Jobs_Per_Year[is.na(rec$Jobs_Per_Year)] = .7722
str(rec)
rec <- as.data.frame(rec, stringsAsFactors = TRUE)
rec$Residence_PUMA = as.factor(rec$Residence_PUMA)
#Some statistics 
#comparing groups by recidivism outcome
gangt<- table(rec$Gang_Affiliated,rec$Recidivism_Within_3years)
chisq.test(gangt)
racet<-table(rec$Race, rec$Recidivism_Within_3years)
chisq.test(racet)
aget<-table(rec$Age_at_Release,rec$Recidivism_Within_3years)
chisq.test(aget)
gendert<-table(rec$Gender,rec$Recidivism_Within_3years)
chisq.test(gendert)
educationt<-table(rec$Education_Level,rec$Recidivism_Within_3years)
chisq.test(educationt)
dependentst<-table(rec$Dependents,rec$Recidivism_Within_3years)
chisq.test(dependentst)
residencet<-table(rec$Residence_PUMA, rec$Recidivism_Within_3years)
chisq.test(residencet)
offenset<-table(rec$Prison_Offense,rec$Recidivism_Within_3years)
chisq.test(offenset)
sentencet<-table(rec$Prison_Years, rec$Recidivism_Within_3years)
chisq.test(sentencet)
felonyt<-table(rec$Prior_Arrest_Episodes_Felony, rec$Recidivism_Within_3years)
chisq.test(felonyt)
misdt<-table(rec$Prior_Arrest_Episodes_Misd, rec$Recidivism_Within_3years)
chisq.test(misdt)
viol<-table(rec$Prior_Arrest_Episodes_Violent, rec$Recidivism_Within_3years)
chisq.test(viol)
prop<-table(rec$Prior_Arrest_Episodes_Property, rec$Recidivism_Within_3years)
chisq.test(prop)
drug<-table(rec$Prior_Arrest_Episodes_Drug, rec$Recidivism_Within_3years)
chisq.test(drug)
pp<-table(rec$Prior_Arrest_Episodes_PPViolationCharges, rec$Recidivism_Within_3years)
chisq.test(pp)
dv<-table(rec$Prior_Arrest_Episodes_DVCharges, rec$Recidivism_Within_3years)
chisq.test(dv)
gun<-table(rec$Prior_Arrest_Episodes_GunCharges, rec$Recidivism_Within_3years)
chisq.test(gun)
cfel<-table(rec$Prior_Conviction_Episodes_Felony, rec$Recidivism_Within_3years)
chisq.test(cfel)
cmis<-table(rec$Prior_Conviction_Episodes_Misd, rec$Recidivism_Within_3years)
chisq.test(cmis)
cviol<-table(rec$Prior_Conviction_Episodes_Viol, rec$Recidivism_Within_3years)
chisq.test(cviol)
cprop<-table(rec$Prior_Conviction_Episodes_Prop, rec$Recidivism_Within_3years)
chisq.test(cprop)
cdrug<-table(rec$Prior_Conviction_Episodes_Drug, rec$Recidivism_Within_3years)
chisq.test(cdrug)
cpp<-table(rec$Prior_Conviction_Episodes_PPViolationCharges, rec$Recidivism_Within_3years)
chisq.test(cpp)
cdv<-table(rec$Prior_Conviction_Episodes_DomesticViolenceCharges, rec$Recidivism_Within_3years)
chisq.test(cdv)
cgun<-table(rec$Prior_Conviction_Episodes_GunCharges, rec$Recidivism_Within_3years)
chisq.test(cgun)
revparole<-table(rec$Prior_Revocations_Parole, rec$Recidivism_Within_3years)
chisq.test(revparole)
revprob<-table(rec$Prior_Revocations_Probation, rec$Recidivism_Within_3years)
chisq.test(revprob)
delinquencyt<-table(rec$Delinquency_Reports, rec$Recidivism_Within_3years)
chisq.test(delinquencyt)
attendancet<-table(rec$Program_Attendances, rec$Recidivism_Within_3years)
chisq.test(attendancet)
absencest<-table(rec$Program_UnexcusedAbsences, rec$Recidivism_Within_3years)
chisq.test(absencest)
residencet<-table(rec$Residence_Changes, rec$Recidivism_Within_3years)
chisq.test(residencet)


MH_condition<-tabpct(rec$Condition_MH_SA, rec$Recidivism_Within_3years, percent = 'row',
                     main = 'Recidivism & Mental health/Substance', xlab = 'MH conditions?', ylab = 'Recidivism',
                     col = c('green','red'))
Cog_condition<-tabpct(rec$Condition_Cog_Ed, rec$Recidivism_Within_3years, percent = 'row',
                      main = 'Recidivism & Cognitive conditions', xlab = 'Cog conditions?', ylab = 'Recidivism',
                      col = c('green','red'))
Oth_condition<-tabpct(rec$Condition_Othe, rec$Recidivism_Within_3years, percent = 'row',
                      main = 'Recidivism & Other conditions', xlab = 'Oth conditions?', ylab = 'Recidivism',
                      col = c('green','red'))
delinquency<-tabpct(rec$Delinquency_Reports, rec$Recidivism_Within_3years, percent = 'row',
                    main = 'Recidivism & delinquency', xlab = 'Delinquencies', ylab = 'Recidivism',
                    col = c('green','red'))
attendance<-tabpct(rec$Program_Attendances, rec$Recidivism_Within_3years, percent = 'row',
                   main = 'Recidivism & Program attendance', xlab = 'Attendances', ylab = 'Recidivism',
                   col = c('green','red'))
absences<-tabpct(rec$Program_UnexcusedAbsences, rec$Recidivism_Within_3years, percent = 'row',
                 main = 'Recidivism & Program absence', xlab = 'Absence', ylab = 'Recidivism',
                 col = c('green','red'))
residence<-tabpct(rec$Residence_Changes, rec$Recidivism_Within_3years, percent = 'row',
                  main = 'Recidivism & Residence changes', xlab = 'Residences', ylab = 'Recidivism',
                  col = c('green','red'))
Misdemeanor<-tabpct(rec$Prior_Arrest_Episodes_Misd, rec$Recidivism_Within_3years, percent = 'row',
                    main = 'Recidivism & Misdemeanor Arrests', xlab = 'Arrests', ylab = 'Recidivism',
                    col = c('green','red'))
felony<-tabpct(rec$Prior_Arrest_Episodes_Felony, rec$Recidivism_Within_3years, percent = 'row',
               main = 'Recidivism & Felony Arrests', xlab = 'Arrests', ylab = 'Recidivism',
               col = c('green','red'))
PPviol<-tabpct(rec$Prior_Arrest_Episodes_PPViolationCharges, rec$Recidivism_Within_3years, percent = 'row',
               main = 'Recidivism & Parole/Probation Violations', xlab = '# Arrests', ylab = 'Recidivism',
               col = c('#336666','#33CC66'))
MH_condition<-tabpct(rec$Condition_MH_SA, rec$Recidivism_Within_3years, percent = 'row',
                     main = 'Recidivism & Mental health/Substance', xlab = 'MH conditions?', ylab = 'Recidivism',
                     col = c('#336666','#33CC66'))
Cog_condition<-tabpct(rec$Condition_Cog_Ed, rec$Recidivism_Within_3years, percent = 'row',
                      main = 'Recidivism & Cognitive conditions', xlab = 'Cog conditions?', ylab = 'Recidivism',
                      col = c('#336666','#33CC66'))
Oth_condition<-tabpct(rec$Condition_Othe, rec$Recidivism_Within_3years, percent = 'row',
                      main = 'Recidivism & Other conditions', xlab = 'Oth conditions?', ylab = 'Recidivism',
                      col = c('#336666','#33CC66'))
delinquency<-tabpct(rec$Delinquency_Reports, rec$Recidivism_Within_3years, percent = 'row',
                    main = 'Recidivism & delinquency', xlab = 'Delinquencies', ylab = 'Recidivism',
                    col = c('#336666','#33CC66'))
attendance<-tabpct(rec$Program_Attendances, rec$Recidivism_Within_3years, percent = 'row',
                   main = 'Recidivism & Program attendance', xlab = 'Attendances', ylab = 'Recidivism',
                   col = c('#336666','#33CC66'))
absences<-tabpct(rec$Program_UnexcusedAbsences, rec$Recidivism_Within_3years, percent = 'row',
                 main = 'Recidivism & Program absence', xlab = 'Absence', ylab = 'Recidivism',
                 col = c('#336666','#33CC66'))
residence<-tabpct(rec$Residence_Changes, rec$Recidivism_Within_3years, percent = 'row',
                  main = 'Recidivism & Residence changes', xlab = 'Residences', ylab = 'Recidivism',
                  col = c('#336666','#33CC66'))
Misdemeanor<-tabpct(rec$Prior_Arrest_Episodes_Misd, rec$Recidivism_Within_3years, percent = 'row',
                    main = 'Recidivism & Misdemeanor Arrests', xlab = 'Arrests', ylab = 'Recidivism',
                    col = c('#336666','#33CC66'))
felony<-tabpct(rec$Prior_Arrest_Episodes_Felony, rec$Recidivism_Within_3years, percent = 'row',
               main = 'Recidivism & Felony Arrests', xlab = 'Arrests', ylab = 'Recidivism',
               col = c('#336666','#33CC66'))
sentence<-tabpct(rec$Prison_Years, rec$Recidivism_Within_3years, percent = 'row',
                 main = 'Recidivism & Sentence', xlab = 'Sentence', ylab = 'Recidivism',
                 col = c('#336666','#33CC66'))
gang<-tabpct(rec$Gang_Affiliated, rec$Recidivism_Within_3years, percent = 'row',
             main = 'Recidivism & Gangs', xlab = 'Gangs', ylab = 'Recidivism',
             col = c('#336666','#33CC66'))
race <-tabpct(rec$Race, rec$Recidivism_Within_3years, percent = 'row',
              main = 'Recidivism & Race', xlab = 'Race', ylab = 'Recidivism',
              col = c('#336666','#33CC66'))
age<-tabpct(rec$Age_at_Release, rec$Recidivism_Within_3years, percent = 'row',
            main = 'Recidivism & Age', xlab = 'Age', ylab = 'Recidivism',
            col = c('#336666','#33CC66'))
gender<-tabpct(rec$Gender, rec$Recidivism_Within_3years, percent = 'row',
               main = 'Recidivism & Gender', xlab = 'Gender', ylab = 'Recidivism',
               col = c('#336666','#33CC66'))
education<-tabpct(rec$Education_Level, rec$Recidivism_Within_3years, percent = 'row',
                  main = 'Recidivism & Education', xlab = 'Education', ylab = 'Recidivism',
                  col = c('#336666','#33CC66'))
dependents<-tabpct(rec$Dependents, rec$Recidivism_Within_3years, percent = 'row',
                   main = 'Recidivism & Dependents', xlab = 'Dependents', ylab = 'Recidivism',
                   col = c('#336666','#33CC66'))
offense<-tabpct(rec$Prison_Offense, rec$Recidivism_Within_3years, percent = 'row',
                main = 'Recidivism & Offence', xlab = 'Offence', ylab = 'Recidivism',
                col = c('#336666','#33CC66'))


sapply(rec[,c(2,3,4,5,6,8,9,10,11,12,13,14,31,32,33,38,39,40,41,50)], function(x) table(x)/nrow(rec))

table(rec$Prison_Years, rec$Recidivism_Within_3years)
sentence
#Quantitative Variables
sd(rec$Avg_Days_per_DrugTest[!is.na(rec$Avg_Days_per_DrugTest)])
sd(rec$DrugTests_THC_Positive[!is.na(rec$DrugTests_THC_Positive)])
sd(rec$DrugTests_Cocaine_Positive[!is.na(rec$DrugTests_Cocaine_Positive)])
sd(rec$DrugTests_Meth_Positive[!is.na(rec$DrugTests_Meth_Positive)])
sd(rec$DrugTests_Other_Positive[!is.na(rec$DrugTests_Other_Positive)])
sd(rec$Percent_Days_Employed[!is.na(rec$Percent_Days_Employed)])
sd(rec$Jobs_Per_Year[!is.na(rec$Jobs_Per_Year)])





hist(rec$Supervision_Risk_Score_First)
hist(rec$Percent_Days_Employed)
hist(rec$Jobs_Per_Year)
hist(rec$DrugTests_THC_Positive)
hist(rec$Avg_Days_per_DrugTest)
hist(rec$Avg_Days_per_DrugTest)

cor(rec[,c(42:48)])

#Partition data into comparison groups

prior_dem<-rec[,c(2,4:6,9:30,50)]

all_data<- rec[,c(2,4:6,9:50)]

post_dem<- rec[,c(2,4:5,9:10,31:50)]

### Logistic Regression models
set.seed(222)

#Using prior data
lr_prior_index<- createDataPartition(prior_dem[,"Recidivism_Within_3years"],
                                     p = 0.7, list = FALSE)
lr_prior_train <-prior_dem[lr_prior_index,]
lr_prior_test <-prior_dem[-lr_prior_index,]
lr_prior_control <- trainControl(method = "cv", number = 10)

lrp_start <-Sys.time()
lr_prior <- train(Recidivism_Within_3years~.,data = prior_dem,
                  method = "glm", trControl = lr_prior_control)
lrp_end <- Sys.time()
lrp_time <-lrp_end-lrp_start
lrp_time

lr_prior_pred <- predict(lr_prior, lr_prior_test, type="raw")
lr_prior_confmatrix<-confusionMatrix(lr_prior_test$Recidivism_Within_3years,
                                     lr_prior_pred,positive = "true")
lr_prior_confmatrix


#Using all data
lr_all_index<- createDataPartition(all_data[,"Recidivism_Within_3years"],
                                   p = 0.7, list = FALSE)
lr_all_train <-all_data[lr_all_index,]
lr_all_test <-all_data[-lr_all_index,]
lr_all_control <- trainControl(method = "cv", number = 10)


lra_start <-Sys.time()
lr_all <- train(Recidivism_Within_3years~.,data = all_data,
                method = "glm", trControl = lr_all_control)
lra_end <- Sys.time()
lra_time <-lra_end-lra_start
lra_time


lr_all_pred <- predict(lr_all, lr_all_test, type="raw")
lr_all_confmatrix <- confusionMatrix(lr_all_test$Recidivism_Within_3years,
                                     lr_all_pred, positive = "true")
lr_all_confmatrix

#Training results
lr_prior_res<-data.frame(lr_prior$resample)
lr_all_res<-data.frame(lr_all$resample)
lr_res<-rbind(lr_prior_res, lr_all_res)
lr_pa<-c(rep('Prior Data', times = 10), rep('All Data', times = 10))
lr_res<-cbind(lr_res, lr_pa)


ggplot(data=lr_res, aes(y= Accuracy, x = Resample, color = lr_pa, group = lr_pa )) + 
  geom_point()+ geom_line()+
  labs(x = 'Cross Validation')+
  theme(panel.background = element_rect(fill = NA),
        panel.grid.major = element_line(colour = "grey50"),
        legend.title = element_blank())+ylim(.6,.8)

#Variable importance

lrallimp<-varImp(lr_all)
plot(lrallimp, top= 10)
lrpriorimp<-varImp(lr_prior)
plot(lrpriorimp, top = 10)

#COMPARING THE RISK SCORES

all_data_risk<-all_data
all_pred <- predict(lr_all, all_data_risk, type= "prob")
prior_pred <- predict(lr_prior, all_data_risk, type= "prob")
all_data_risk<-cbind(all_data_risk, all_risk = all_pred$true)
all_data_risk<-cbind(all_data_risk, prior_risk = prior_pred$true)

all_data_risk$risk_change = all_data_risk$all_risk-all_data_risk$prior_risk
all_data_risk$change = "Higher"
all_data_risk$change[all_data_risk$risk_change<0] = "Lower"


pdr<-ggplot(all_data_risk, aes(x = prior_risk, fill = Recidivism_Within_3years,))+
  geom_histogram(binwidth = .01,position = "identity",alpha = 0.5)+
  scale_fill_manual(values = c("#009933", "#003333"))+
  theme(panel.background = element_rect(fill = NA),
        panel.grid.major = element_line(colour = "grey50"))+
  labs(title = "Risk Score - Prior Data",x = '', y = '',fill = "Recidivism")
pdr


adr<-ggplot(all_data_risk, aes(x = all_risk, fill = Recidivism_Within_3years))+
  geom_histogram(binwidth = .01,position = "identity",color = 'grey50',alpha = 0.5)+
  scale_fill_manual(values = c("#009933", "#003333"))+
  theme(panel.background = element_rect(fill = NA),
        panel.grid.major = element_line(colour = "grey50"))+
  labs(title = "Risk Score - All Data",x = '', y = '',fill = "Recidivism")
adr


cdr<-ggplot(all_data_risk, aes(x = risk_change))+
  geom_histogram(binwidth = .02,position = "identity", alpha = .5,
                 fill = '#003333',color= 'grey50')+
  theme(panel.background = element_rect(fill = NA),
        panel.grid.major = element_line(colour = "grey50"),
  )+labs(x = '', y = '')
cdr



mean(all_data_risk$risk_change)
mean(all_data_risk$all_risk)
mean(all_data_risk$prior_risk)
mean(all_data_risk$all_risk[all_data_risk$Recidivism_Within_3years == 'true'])
mean(all_data_risk$all_risk[all_data_risk$Recidivism_Within_3years == 'false'])
mean(all_data_risk$prior_risk[all_data_risk$Recidivism_Within_3years == 'true'])
mean(all_data_risk$prior_risk[all_data_risk$Recidivism_Within_3years == 'false'])


##CHI SQUARE

lower_prob <- all_data_risk[all_data_risk$change == "Lower",]
higher_prob <- all_data_risk[all_data_risk$change == "Higher",]

res_changes <- table(all_data_risk$change, all_data_risk$Residence_Changes)
chisq.test(res_changes)

plot(res_changes)

prog_att<-table(all_data_risk$change, all_data_risk$Program_Attendances)
chisq.test(prog_att)

prog_abs<-table(all_data_risk$change, all_data_risk$Program_UnexcusedAbsences)
ch_pa<-chisq.test(prog_abs)
summary(ch_pa)


table(all_data_risk$change, all_data_risk$Delinquency_Reports)

#EMPLOYMENT
wilcox.test(higher_prob$Percent_Days_Employed,
            lower_prob$Percent_Days_Employed, exact= F)

ggplot(higher_prob, aes(x = Percent_Days_Employed)
) +geom_histogram(binwidth = .05,position = "identity", fill = '#003333',
                  alpha = 0.5)
ggplot(lower_prob, aes(x = Percent_Days_Employed)
) +geom_histogram(binwidth = .05,position = "identity", fill = '#003333',
                  alpha = 0.5)

wilcox.test(higher_prob$Jobs_Per_Year,
            lower_prob$Jobs_Per_Year, exact= F)

ggplot(all_data_risk, aes(x = Jobs_Per_Year,fill = change,
)) +geom_histogram(binwidth = .1,position = "identity",
                   alpha = 0.5)

##Drug Use
wilcox.test(higher_prob$Avg_Days_per_DrugTest,
            lower_prob$Avg_Days_per_DrugTest, exact= F)
wilcox.test(higher_prob$DrugTests_Cocaine_Positive,
            lower_prob$DrugTests_Cocaine_Positive, exact= F)
wilcox.test(higher_prob$DrugTests_THC_Positive,
            lower_prob$DrugTests_THC_Positive, exact= F)
wilcox.test(higher_prob$DrugTests_Meth_Positive,
            lower_prob$DrugTests_Meth_Positive, exact= F)
wilcox.test(higher_prob$DrugTests_Other_Positive,
            lower_prob$DrugTests_Other_Positive, exact= F)

##KNN
knn_data_prior<-prior_dem
knn_data_all <-all_data
knn_data_post <-post_dem


knn_data_prior[1:26]= sapply(knn_data_prior[1:26], unclass)
normalize <- function(x){(x - min(x)) / (max(x) - min(x))}
knn_data_prior[1:26]=sapply(knn_data_prior[1:26], normalize)
summary(knn_data_prior)

knn_data_all[1:45]= sapply(knn_data_all[1:45], unclass)
knn_data_all[1:45]= sapply(knn_data_all[1:45], normalize)
summary(knn_data_all)

knn_data_post[1:24]= sapply(knn_data_post[1:24], unclass)
knn_data_post[1:24]=sapply(knn_data_post[1:24], normalize)
summary(knn_data_post)

set.seed(222)

##Using prior data
knn_prior_index<- createDataPartition(knn_data_prior[,"Recidivism_Within_3years"],
                                      p = 0.7, list = FALSE)
knn_prior_train <-knn_data_prior[knn_prior_index,]
knn_prior_test <-knn_data_prior[-knn_prior_index,]

knn_prior_control <- trainControl(method = "cv", number = 10)

kpr_start <-Sys.time()
knn_prior <- train(Recidivism_Within_3years~.,data = knn_prior_train,
                   method = "knn", trControl = knn_prior_control,
                   tuneGrid =data.frame(k=seq(5,100,by=10)))
kpr_end <- Sys.time()
kpr_time <-kpr_end-kpr_start
kpr_time

knn_prior_pred <- predict(knn_prior, knn_prior_test)
confusionMatrix(knn_prior_test$Recidivism_Within_3years,knn_prior_pred,
                positive = 'true')

###KNN USING ALL DATA
knn_all_index<- createDataPartition(knn_data_all[,"Recidivism_Within_3years"],
                                    p = 0.7, list = FALSE)
knn_all_train <-knn_data_all[knn_all_index,]
knn_all_test <-knn_data_all[-knn_all_index,]

knn_all_control <- trainControl(method = "cv", number = 10)

ka_start <- Sys.time()
knn_all <- train(Recidivism_Within_3years~.,data = knn_all_train,
                 method = "knn", trControl = knn_all_control, 
                 tuneGrid =data.frame(k=seq(5,100,by=10)))
ka_end <- Sys.time()
ka_time <-ka_end-ka_start
ka_time

knn_all_pred <- predict(knn_all, knn_all_test)
confusionMatrix(knn_all_test$Recidivism_Within_3years,knn_all_pred,
                positive = 'true')


##USING POST DATA
knn_post_index<- createDataPartition(knn_data_post[,"Recidivism_Within_3years"],
                                     p = 0.7, list = FALSE)
knn_post_train <-knn_data_post[knn_post_index,]
knn_post_test <-knn_data_post[-knn_post_index,]

knn_post_control <- trainControl(method = "cv", number = 10)
kpo_start <- Sys.time()
knn_post <- train(Recidivism_Within_3years~.,data = knn_post_train,
                  method = "knn", trControl = knn_post_control, 
                  tuneGrid =data.frame(k=seq(5,100,by=10)))
kpo_end<-Sys.time()
kpo_time <-kpo_end-kpo_start
kpo_time

knn_post_pred <- predict(knn_post, knn_post_test)
confusionMatrix(knn_post_test$Recidivism_Within_3years,knn_post_pred,
                positive = 'true')

knn_pre_res<-data.frame(knn_prior$resample)
knn_post_res<-data.frame(knn_post$resample)
knn_all_res<-data.frame(knn_all$resample)
knn_res<-rbind(knn_pre_res, knn_post_res, knn_all_res)
knn_pa<-c(rep("Prior Data", times = 10), rep("Post Data", times = 10), rep("All Data", times = 10))
knn_res<-cbind(knn_res, knn_pa)


ggplot(data=knn_res, aes(y= Accuracy, x = Resample, color = knn_pa, group = knn_pa )) + 
  geom_point()+ geom_line()+ labs(x = 'Cross Validation')+
  theme(panel.background = element_rect(fill = NA),
        panel.grid.major = element_line(colour = "grey50"), legend.title = element_blank())+
  ylim(.60,.75)


knnaimp<-varImp(knn_all)
plot(knnaimp, top =10 , color = 'red')
knnprimp<-varImp(knn_prior)
plot(knnprimp, top =10, color = 'red')
knnpoimp<-varImp(knn_post)
plot(knnpoimp, top = 10)

###Random Forest
set.seed(222)

#Using prior data
rf_prior_index<- createDataPartition(prior_dem[,"Recidivism_Within_3years"],
                                     p = 0.7, list = FALSE)
rfprior_train <-prior_dem[rf_prior_index,]
rfprior_test <- prior_dem[-rf_prior_index,]
prior_control <- trainControl(method = "cv", number = 10)
rfp_start <-Sys.time()
rf_prior <- train(Recidivism_Within_3years~.,data = rfprior_train,
                  method = "rf", trControl = prior_control, tuneLength = 10,
                  importance = TRUE, ntree = 100)
rfp_end <-Sys.time()
rfp_time <-rfp_end-rfp_start
rfp_time

rf_prior_pred <- predict(rf_prior, rfprior_test)
rf_prior_cm<-confusionMatrix(rfprior_test$Recidivism_Within_3years,rf_prior_pred,
                positive = "true")
rf_prior_cm

#Using all data
rf_all_index<- createDataPartition(all_data[,"Recidivism_Within_3years"],
                                   p = 0.7, list = FALSE)
rfall_train <-all_data[rf_all_index,]
rfall_test <- all_data[-rf_all_index,]
all_control <- trainControl(method = "cv", number = 10)

rfa_start <-Sys.time()
rf_all <- train(Recidivism_Within_3years~.,data = rfall_train,
                method = "rf", trControl = all_control, tuneLength = 10,
                importance = TRUE, ntree = 100)
rfa_end<-Sys.time()
rfa_time <- rfa_end-rfa_start
rfa_time

rf_all_pred <- predict(rf_all, rfall_test)

rf_all_cm<-confusionMatrix(rfall_test$Recidivism_Within_3years,rf_all_pred,
                positive = "true")
rf_all_cm

#Training results
rf_prior_res<-data.frame(rf_prior$resample)
rf_all_res<-data.frame(rf_all$resample)
rf_res<-rbind(rf_prior_res, rf_all_res)
rf_pa<-c(rep('Prior Data', times = 10), rep('All Data', times = 10))
rf_res<-cbind(rf_res, rf_pa)

ggplot(data=rf_res, aes(y= Accuracy, x = Resample, color = rf_pa, group = rf_pa )) + 
  geom_point()+ geom_line()+ labs(x = 'Cross Validation')+
  theme(panel.background = element_rect(fill = NA),
        panel.grid.major = element_line(colour = "grey50"),
        legend.title = element_blank())+ ylim(.6,.8)

#Variable importance
rfimp<-varImp(rf_all)
plot(rfimp, top =10)
rf_pimp<-varImp(rf_prior)
plot(rf_pimp, top =10)

###Model info
pred_model <- c('Knn','Knn', 'Random Forest', 'Random Forest',
                'Logistic Regression','Logistic Regression')
model_data<-c('Prior','All','Prior','All','Prior','All')
accuracy <- c(65.9, 68.3,66.3,72.7,68.2,71.9)
precision <-c(66.4,69.4,67.5,73.1,69.2,73.3)
recall<-c(82.2,80.1,79.5,82.8,80.3,80.3)
specificity <-c(43.9,52.5,48.6,59,52,60.6)

model_results <-data.frame(pred_model,model_data,accuracy,precision,recall,specificity)

model_acc<-ggplot(data=model_results, aes(x = accuracy, y = pred_model, fill = model_data)) +
  geom_bar(stat="identity",position=position_dodge(),color = 'black',width = .75, alpha = .75)+
  scale_fill_manual(values = c("#003333","#99cccc"))+ 
  theme(legend.title = element_blank(),panel.background = element_rect(fill = NA),
        panel.grid.major = element_line(colour = "grey50"),
  )+labs(title = "Model Accuracy",x = '', y = '') +scale_x_continuous(breaks=seq(0,75,10))
model_acc

model_prec<-ggplot(data=model_results, aes(x = precision, y = pred_model, fill = model_data)) +
  geom_bar(stat="identity",position=position_dodge(),color = 'black',width = .75, alpha = .75)+
  scale_fill_manual(values = c("#003333","#99cccc"))+ 
  theme(legend.title = element_blank(),panel.background = element_rect(fill = NA),
        panel.grid.major = element_line(colour = "grey50"),
  )+labs(title = "Model Precision",x = '', y = '') +scale_x_continuous(breaks=seq(0,75,10))
model_prec

model_recall<-ggplot(data=model_results, aes(x = recall, y = pred_model, fill = model_data)) +
  geom_bar(stat="identity",position=position_dodge(),color = 'black',width = .75, alpha = .75)+
  scale_fill_manual(values = c("#003333","#99cccc"))+ 
  theme(legend.title = element_blank(),panel.background = element_rect(fill = NA),
        panel.grid.major = element_line(colour = "grey50"),
  )+labs(title = "Model Recall",x = '', y = '') +scale_x_continuous(breaks=seq(0,80,10))
model_recall

model_neg<-ggplot(data=model_results, aes(x = specificity, y = pred_model, fill = model_data)) +
  geom_bar(stat="identity",position=position_dodge(),color = 'black',width = .75, alpha = .75)+
  scale_fill_manual(values = c("#003333","#99cccc"))+ 
  theme(legend.title = element_blank(),panel.background = element_rect(fill = NA),
        panel.grid.major = element_line(colour = "grey50"),
  )+labs(title = "Model Specificity",x = '', y = '') +scale_x_continuous(breaks=seq(0,80,10))
model_neg
recy<-all_data_risk[all_data_risk$Recidivism_Within_3years == 'true',]
recn<-all_data_risk[all_data_risk$Recidivism_Within_3years == 'false',]
summary(recy)
summary(recn)
wilcox.test(recy$Avg_Days_per_DrugTest, recn$Avg_Days_per_DrugTest)
wilcox.test(recy$DrugTests_THC_Positive, recn$DrugTests_THC_Positive)
wilcox.test(recy$DrugTests_Cocaine_Positive,recn$DrugTests_Cocaine_Positive)
wilcox.test(recy$DrugTests_Meth_Positive, recn$DrugTests_Meth_Positive)
wilcox.test(recy$DrugTests_Other_Positive, recn$DrugTests_Other_Positive)
wilcox.test(recy$Jobs_Per_Year, recn$Jobs_Per_Year)
wilcox.test(recy$Percent_Days_Employed, recn$Percent_Days_Employed)




```

